Repository ProjectMeowInc/meow-mail.frontend, pull requests merged in 2024-05, with the labels that each got.

#88 Сделана смена пароля по 2 факторной аутентификации
  src/entities/Auth/api/AuthApi.ts
  src/entities/Auth/models/requests/Get2FATokenRequestType.ts
  src/entities/Auth/models/responses/Get2FATokenResponseType.ts
  src/pages/SettingsPage/UI/AddTwoFactor/AddToFactor.tsx
  src/pages/SettingsPage/UI/AddTwoFactor/addToFactor.module.css
  src/pages/SettingsPage/UI/ChangePasswordForm/ChangePasswordForm.tsx
  src/pages/SettingsPage/UI/ChangePasswordForm/useChangePasswordForm.ts
  src/pages/SettingsPage/UI/Check2FAForm/Check2FAForm.tsx
  src/pages/SettingsPage/UI/Check2FAForm/chech2FAForm.module.css
  src/shared/services/TokenService.ts
  src/shared/utils/query.ts
Labels: feature

#89 Сделано получение информации о аккаунте
  src/entities/Auth/api/AuthApi.ts
  src/entities/Auth/models/responses/IGetInformationAboutUserResponse.ts
  src/entities/Auth/redusers/userSlice.ts
  src/pages/SettingsPage/UI/AddTwoFactor/AddToFactor.tsx
  src/pages/SettingsPage/UI/AddTwoFactor/addToFactor.module.css
  src/pages/SettingsPage/UI/AddTwoFactor/useAddToFactor.ts
  src/pages/auth/AuthPage/useAuthPage.ts
Labels: feature

#90 Add pretty email editor
  package.json
  src/index.css
  src/shared/components/Input/InputEmail/inputEmail.module.css
  src/shared/components/SendEmailForm/SendEmailForm.tsx
  src/shared/components/SendEmailForm/sendEmailForm.module.css
  src/shared/components/SendEmailForm/useSendEmailForm.ts
  src/shared/icons/editor/block quote.png
  src/shared/icons/editor/bold.png
  src/shared/icons/editor/bulleted list.png
  src/shared/icons/editor/italic.png
  src/shared/icons/editor/numbered list.png
  src/shared/icons/editor/strikethrough.png
Labels: feature

#91 fix build
  package.json
  src/global.d.ts
Labels: bug, build

#92 Общие правки проекта
  src/entities/Auth/models/responses/IGetInformationAboutUserResponse.ts
  src/entities/Auth/redusers/userSlice.ts
  src/index.css
  src/pages/AdminUserPage/AdminUserPage.tsx
  src/pages/AdminUserPage/adminUserPage.module.css
  src/pages/EmailGroupPage/EmailGroupPage.tsx
  src/pages/EmailGroupPage/emailGroupPage.module.css
  src/pages/LetterPage/LetterPage.tsx
  src/pages/LetterPage/letterPage.module.css
  src/pages/LettersPage/LettersPage.tsx
  src/pages/SentEmailsPage/SentEmailsPage.tsx
  src/pages/SettingsPage/UI/AddTwoFactor/addToFactor.module.css
  src/pages/SettingsPage/UI/Check2FAForm/chech2FAForm.module.css
  src/pages/UI/EmptyInboxPlaceholder/EmptyInboxPlaceholder.tsx
  src/pages/UI/EmptyInboxPlaceholder/emptyInboxPlaceholder.module.css
  src/pages/UI/MobilePaginationControls/mobilePaginationControls.module.css
  src/pages/UI/PaginationControls/paginationControls.module.css
  src/pages/auth/AuthPage/useAuthPage.ts
  src/shared/components/EmailGroup/EmailGroup.tsx
  src/shared/components/EmailGroup/UI/EmailGroupItem/EmailGroupItem.tsx
  src/shared/components/Header/HeaderDesktop/HeaderDesktop.tsx
  src/shared/components/Header/HeaderDesktop/UI/AdminDropDownMenu/AdminDropDownMenu.tsx
  src/shared/components/Header/HeaderDesktop/UI/AdminDropDownMenu/UI/AdminDropDownMenuItem/AdminDropDownMenuItem.tsx
  src/shared/components/Header/HeaderDesktop/headerDesktop.module.css
  src/shared/components/Header/HeaderDesktop/useHeaderDesktop.ts
  src/shared/components/Header/HeaderMobile/HeaderMobile.tsx
  src/shared/components/Header/HeaderMobile/UI/MenuItem/MenuItem.tsx
  src/shared/components/SendEmailForm/sendEmailForm.module.css
  src/shared/images/cat.png
  src/shared/services/FormatterService.ts
Labels: bug, design, refactoring

#93 Исправлен порядок вывода писем
  src/shared/services/FormatterService.ts
Labels: bug

#94 Исправлен поиск с русским языком
  package.json
  src/entities/Email/api/emailApi.ts
  src/shared/components/Header/HeaderMobile/HeaderMobile.tsx
  src/shared/components/Header/HeaderMobile/headerMobile.module.css
  src/shared/components/Header/HeaderMobile/useHeaderMobile.ts
Labels: bug

#95 Add fast auth
  src/pages/auth/AuthPage/useAuthPage.ts
  src/shared/services/AuthService.ts
Labels: feature

#96 Add display user mailbox
  src/entities/User/models/IGetUserListResponse.ts
  src/pages/AdminUserPage/AdminUserPage.tsx
  src/pages/AdminUserPage/UI/UserItem/UserItem.tsx
  src/pages/AdminUserPage/UI/UserItem/userItem.module.css
Labels: feature

#97 Сделано уведомление о успешной регистрации
  src/pages/auth/RegistrationPage/useRegistrationPage.ts
Labels: bug, design

#99 Исправление русского языка и названия компонентов
  src/pages/SettingsPage/SettingsPage.tsx
  src/pages/SettingsPage/UI/AddTwoFactor/AddTwoFactor.tsx
  src/pages/SettingsPage/UI/AddTwoFactor/addTwoFactor.module.css
  src/pages/SettingsPage/UI/AddTwoFactor/useAddTwoFactor.ts
Labels: bug

#100 Fix ru lang
  src/pages/SettingsPage/UI/AddTwoFactor/AddTwoFactor.tsx
Labels: bug

#103 Move notification to lower
  src/index.tsx
  src/shared/services/AlertService.ts
Labels: design

#104 Fix type check
  src/pages/SettingsPage/UI/ChangePasswordForm/useChangePasswordForm.ts
Labels: bug

#105 fix state manager
  src/pages/AdminUserPage/UI/UserItem/userItem.module.css
  src/pages/LettersPage/useLettersPage.ts
  src/pages/auth/AuthPage/useAuthPage.ts
  src/shared/hooks/useEffectAsync.ts
Labels: bug

#106 Fix telegram code with out telegram
  src/entities/Theme/slices/themeSlice.ts
  src/pages/auth/AuthPage/UI/TwoFactorAuth/TwoFactorAuth.tsx
  src/pages/auth/AuthPage/useAuthPage.ts
Labels: bug, design

#108 Сделана проверка на наличие токена
  src/pages/auth/AuthPage/useAuthPage.ts
  src/shared/services/AuthService.ts
Labels: bug, feature
