Repository ProjectMeowInc/meow-mail.frontend, pull requests merged in 2024-04, with the labels that each got.

#52 Сделана админ панель
  src/App.tsx
  src/consts.ts
  src/entities/Auth/redusers/userSlice.ts
  src/entities/User/api/userApi.ts
  src/entities/User/models/IGetUserListResponse.ts
  src/entities/User/models/IUpdateUserRoleById.ts
  src/entities/User/types/UserRoleType.ts
  src/index.css
  src/pages/AdminUserPage/AdminUserPage.tsx
  src/pages/AdminUserPage/UI/UserItem/UserItem.tsx
  src/pages/AdminUserPage/UI/UserItem/useUserItem.ts
  src/pages/AdminUserPage/UI/UserItem/userItem.module.css
  src/pages/AdminUserPage/adminUserPage.module.css
  src/pages/AdminUserPage/useAdminPage.ts
  src/pages/auth/AuthPage/useAuthPage.ts
  src/shared/components/Header/HeaderDesktop/HeaderDesktop.tsx
  src/shared/components/Header/HeaderDesktop/UI/AdminDropDownMenu/AdminDropDownMenu.tsx
  src/shared/components/Header/HeaderDesktop/UI/AdminDropDownMenu/UI/AdminDropDownMenuItem/AdminDropDownMenuItem.tsx
  src/shared/components/Header/HeaderDesktop/UI/AdminDropDownMenu/UI/AdminDropDownMenuItem/adminDropDownMenuItem.module.css
  src/shared/components/Header/HeaderDesktop/UI/AdminDropDownMenu/adminDropDownMenu.module.css
  src/shared/icons/light.svg
  src/shared/services/TokenService.ts
  src/store.ts
Labels: feature

#53 Style fix
  package.json
  src/entities/Auth/api/AuthApi.ts
  src/entities/Email/api/emailApi.ts
  src/entities/EmailGroup/api/EmailGroupApi.ts
  src/entities/EmailGroup/models/requests/ICreateEmailGroupRequest.ts
  src/entities/EmailGroup/models/requests/IGetEmailByEmailGroupRequest.ts
  src/entities/EmailGroup/models/responses/ICreateEmailGroupResponse.ts
  src/entities/EmailGroup/models/responses/IGetEmailGroupsResponse.ts
  src/entities/EmailGroup/models/responses/IGetEmailsByEmailGroupResponse.ts
  src/pages/AdminUserPage/AdminUserPage.tsx
  src/pages/AdminUserPage/UI/UserItem/userItem.module.css
  src/pages/AdminUserPage/useAdminUserPage.ts
  src/pages/EmailGroupPage/EmailGroupPage.tsx
  src/pages/EmailGroupPage/useEmailGroupPage.ts
  src/pages/LetterPage/LetterPage.tsx
  src/pages/LettersPage/LettersPage.tsx
  src/pages/auth/AgreementProcessingPersonalDataPage/AgreementProcessingPersonalDataPage.tsx
  src/pages/auth/AgreementProcessingPersonalDataPage/agreementProcessingPersonalDataPage.module.css
  src/pages/auth/UI/Form/Form.tsx
  src/pages/auth/UI/Form/form.module.css
  src/shared/components/Checkbox/Checkbox.tsx
  src/shared/components/Checkbox/checkbox.module.css
  src/shared/components/EmailGroup/EmailGroup.tsx
  src/shared/components/EmailGroup/UI/CreateEmailGroupModal/CreateEmailGroupModal.tsx
  src/shared/components/EmailGroup/UI/CreateEmailGroupModal/createEmailGroupModal.module.css
  src/shared/components/EmailGroup/UI/CreateEmailGroupModal/useCreateEmailGroupModal.ts
  src/shared/components/EmailGroup/UI/EmailGroupItem/EmailGroupItem.tsx
  src/shared/components/EmailGroup/UI/EmailGroupItem/emailGroupItem.module.css
  src/shared/components/EmailGroup/UI/EmailGroupItem/useEmailGroupItem.ts
  src/shared/components/EmailGroup/emailGroup.module.css
  src/shared/components/EmailGroup/useEmailGroup.ts
  src/shared/components/Header/HeaderDesktop/UI/AdminDropDownMenu/UI/AdminDropDownMenuItem/adminDropDownMenuItem.module.css
  src/shared/components/Header/HeaderDesktop/UI/AdminDropDownMenu/adminDropDownMenu.module.css
  src/shared/components/Input/Input.tsx
  src/shared/components/Preloader/Preloader.tsx
  src/shared/components/Preloader/preloader.css
  src/shared/utils/query.ts
  tsconfig.json
  vite.config.ts
  vite.env.d.ts
Labels: refactoring

#54 Сделана темная тема
  src/App.tsx
  src/entities/Theme/slices/themeSlice.ts
  src/index.module.css
  src/index.tsx
  src/pages/LetterPage/letterPage.module.css
  src/pages/auth/AuthPage/authPage.module.css
  src/pages/auth/RegistrationPage/registrationPage.module.css
  src/shared/components/Email/email.module.css
  src/shared/components/EmailGroup/emailGroup.module.css
  src/shared/components/Header/HeaderDesktop/UI/MenuItem/menuItem.module.css
  src/shared/layouts/RootLayout/rootLayout.module.css
  src/store.ts
Labels: feature, design

#55 fix theme
  src/index.module.css
Labels: bug

#56 Fix dark theme #2
  index.html
  src/App.tsx
  src/index.css
  src/index.tsx
Labels: bug

#67 Сделана страница с настройками
  src/App.tsx
  src/entities/Auth/api/AuthApi.ts
  src/entities/Auth/models/requests/IChangePasswordRequest.ts
  src/entities/Theme/slices/themeSlice.ts
  src/pages/SettingsPage/SettingsPage.tsx
  src/pages/SettingsPage/UI/ChangePasswordForm/ChangePasswordForm.tsx
  src/pages/SettingsPage/UI/ChangePasswordForm/changePasswordForm.module.css
  src/pages/SettingsPage/UI/ChangePasswordForm/useChangePasswordForm.ts
  src/pages/SettingsPage/UI/ChangeTheme/ChangeTheme.tsx
  src/pages/SettingsPage/UI/ChangeTheme/changeTheme.module.css
  src/pages/SettingsPage/UI/ChangeTheme/useChangeTheme.ts
  src/pages/SettingsPage/UI/SettingWrapper/SettingsWrapper.tsx
  src/pages/SettingsPage/UI/SettingWrapper/settingWrapper.module.css
  src/shared/components/ Switch/Switch.tsx
  src/shared/components/ Switch/switch.module.css
  src/shared/components/ Switch/useSwitch.ts
  src/shared/components/Header/HeaderDesktop/HeaderDesktop.tsx
  src/shared/components/Header/HeaderDesktop/useHeaderDesktop.ts
  src/shared/layouts/RootLayout/rootLayout.module.css
Labels: feature, design

#68 Изменена проверка на наличие data
  src/pages/AdminUserPage/useAdminUserPage.ts
  src/pages/EmailGroupPage/useEmailGroupPage.ts
  src/pages/LetterPage/useLetterPage.ts
  src/pages/LettersPage/useLettersPage.ts
  src/pages/SettingsPage/UI/ChangePasswordForm/useChangePasswordForm.ts
  src/pages/auth/AuthPage/useAuthPage.ts
  src/pages/auth/RegistrationPage/useRegistrationPage.ts
  src/shared/components/Email/useEmail.ts
  src/shared/components/EmailGroup/UI/CreateEmailGroupModal/useCreateEmailGroupModal.ts
  src/shared/components/EmailGroup/UI/EmailGroupItem/useEmailGroupItem.ts
  src/shared/components/EmailGroup/useEmailGroup.ts
  src/shared/components/SendEmailForm/useSendEmailForm.ts
  src/shared/layouts/RootLayout/useRootLayout.ts
  src/shared/utils/hasData.ts
Labels: refactoring

#69 Изменена логика создания группы писем
  src/entities/EmailGroup/models/requests/ICreateEmailGroupRequest.ts
  src/entities/EmailGroup/models/responses/IGetEmailGroupsResponse.ts
  src/shared/components/EmailGroup/EmailGroup.tsx
  src/shared/components/EmailGroup/UI/CreateEmailGroupModal/CreateEmailGroupModal.tsx
  src/shared/components/EmailGroup/UI/CreateEmailGroupModal/createEmailGroupModal.module.css
  src/shared/components/EmailGroup/UI/CreateEmailGroupModal/useCreateEmailGroupModal.ts
  src/shared/components/EmailGroup/UI/EmailGroupItem/EmailGroupItem.tsx
  src/shared/components/EmptyTag/EmptyTag.tsx
  src/shared/components/Input/DefaultInput/DefaultInput.tsx
  src/shared/components/Input/Input.tsx
  src/shared/components/Mailbox/Mailbox.tsx
  src/shared/components/Mailbox/mailbox.module.css
  src/shared/events/IOnChangeEvent.ts
Labels: bug, refactoring

#71 Feature/change group logic
  src/App.tsx
  src/entities/Auth/api/AuthApi.ts
  src/entities/Auth/models/requests/IChangePasswordRequest.ts
  src/entities/EmailGroup/models/requests/ICreateEmailGroupRequest.ts
  src/entities/EmailGroup/models/responses/IGetEmailGroupsResponse.ts
  src/entities/Theme/slices/themeSlice.ts
  src/pages/AdminUserPage/useAdminUserPage.ts
  src/pages/EmailGroupPage/useEmailGroupPage.ts
  src/pages/LetterPage/useLetterPage.ts
  src/pages/LettersPage/useLettersPage.ts
  src/pages/SettingsPage/SettingsPage.tsx
  src/pages/SettingsPage/UI/ChangePasswordForm/ChangePasswordForm.tsx
  src/pages/SettingsPage/UI/ChangePasswordForm/changePasswordForm.module.css
  src/pages/SettingsPage/UI/ChangePasswordForm/useChangePasswordForm.ts
  src/pages/SettingsPage/UI/ChangeTheme/ChangeTheme.tsx
  src/pages/SettingsPage/UI/ChangeTheme/changeTheme.module.css
  src/pages/SettingsPage/UI/ChangeTheme/useChangeTheme.ts
  src/pages/SettingsPage/UI/SettingWrapper/SettingsWrapper.tsx
  src/pages/SettingsPage/UI/SettingWrapper/settingWrapper.module.css
  src/pages/auth/AuthPage/useAuthPage.ts
  src/pages/auth/RegistrationPage/useRegistrationPage.ts
  src/shared/components/ Switch/Switch.tsx
  src/shared/components/ Switch/switch.module.css
  src/shared/components/ Switch/useSwitch.ts
  src/shared/components/Email/useEmail.ts
  src/shared/components/EmailGroup/EmailGroup.tsx
  src/shared/components/EmailGroup/UI/CreateEmailGroupModal/CreateEmailGroupModal.tsx
  src/shared/components/EmailGroup/UI/CreateEmailGroupModal/createEmailGroupModal.module.css
  src/shared/components/EmailGroup/UI/CreateEmailGroupModal/useCreateEmailGroupModal.ts
  src/shared/components/EmailGroup/UI/EmailGroupItem/EmailGroupItem.tsx
  src/shared/components/EmailGroup/UI/EmailGroupItem/useEmailGroupItem.ts
  src/shared/components/EmailGroup/useEmailGroup.ts
  src/shared/components/EmptyTag/EmptyTag.tsx
  src/shared/components/Header/HeaderDesktop/HeaderDesktop.tsx
  src/shared/components/Header/HeaderDesktop/useHeaderDesktop.ts
  src/shared/components/Input/DefaultInput/DefaultInput.tsx
  src/shared/components/Input/Input.tsx
  src/shared/components/Mailbox/Mailbox.tsx
  src/shared/components/Mailbox/mailbox.module.css
  src/shared/components/SendEmailForm/useSendEmailForm.ts
  src/shared/events/IOnChangeEvent.ts
  src/shared/layouts/RootLayout/rootLayout.module.css
  src/shared/layouts/RootLayout/useRootLayout.ts
  src/shared/utils/hasData.ts
Labels: bug, feature

#72 Сделана страница отправленных
  src/App.tsx
  src/pages/SentEmailsPage/SentEmailsPage.tsx
  src/pages/SentEmailsPage/sentEmailsPage.module.css
  src/pages/SentEmailsPage/useSentEmailsPage.ts
  src/shared/components/Header/HeaderDesktop/HeaderDesktop.tsx
  src/shared/components/Header/HeaderDesktop/UI/MenuItem/MenuItem.tsx
Labels: feature

#74 Add clean up storage after login
  src/pages/AdminUserPage/useAdminUserPage.ts
  src/pages/EmailGroupPage/useEmailGroupPage.ts
  src/pages/LetterPage/useLetterPage.ts
  src/pages/LettersPage/useLettersPage.ts
  src/pages/SentEmailsPage/useSentEmailsPage.ts
  src/pages/SettingsPage/UI/ChangePasswordForm/useChangePasswordForm.ts
  src/pages/auth/AuthPage/useAuthPage.ts
  src/pages/auth/RegistrationPage/useRegistrationPage.ts
  src/shared/components/Email/useEmail.ts
  src/shared/components/EmailGroup/UI/CreateEmailGroupModal/useCreateEmailGroupModal.ts
  src/shared/components/EmailGroup/UI/EmailGroupItem/useEmailGroupItem.ts
  src/shared/components/EmailGroup/useEmailGroup.ts
  src/shared/components/SendEmailForm/useSendEmailForm.ts
  src/shared/layouts/RootLayout/useRootLayout.ts
  src/shared/utils/hasData.ts
  src/store.ts
Labels: bug

#75 Исправлено авто обновление токена доступа
  package.json
  src/entities/Auth/api/AuthApi.ts
  src/shared/services/TokenService.ts
  src/shared/utils/query.ts
Labels: bug

#78 Сделаны подключение и авторизация по 2-этапной аутентификации
  src/entities/Auth/api/AuthApi.ts
  src/entities/Auth/models/requests/AuthorizationRequestV2Type.ts
  src/entities/Auth/models/requests/IAuthorizationRequest.ts
  src/entities/Auth/models/responses/AuthorizationResponseV2Type.ts
  src/entities/Auth/models/responses/IAuthorizationResponse.ts
  src/entities/Auth/models/responses/IConnectTelegramResponse.ts
  src/pages/SettingsPage/SettingsPage.tsx
  src/pages/SettingsPage/UI/AddTwoFactor/AddToFactor.tsx
  src/pages/SettingsPage/UI/AddTwoFactor/addToFactor.module.css
  src/pages/SettingsPage/UI/AddTwoFactor/useAddToFactor.ts
  src/pages/SettingsPage/UI/ChangePasswordForm/changePasswordForm.module.css
  src/pages/SettingsPage/UI/ChangeTheme/changeTheme.module.css
  src/pages/SettingsPage/UI/SettingWrapper/SettingsWrapper.tsx
  src/pages/SettingsPage/UI/SettingWrapper/settingWrapper.module.css
  src/pages/auth/AuthPage/AuthPage.tsx
  src/pages/auth/AuthPage/UI/TwoFactorAuth/TwoFactorAuth.tsx
  src/pages/auth/AuthPage/UI/TwoFactorAuth/twoFactorAuth.module.css
  src/pages/auth/AuthPage/useAuthPage.ts
  src/shared/components/Header/HeaderDesktop/HeaderDesktop.tsx
  src/shared/icons/clipboard-copy.svg
  src/shared/images/QRCode.png
Labels: feature

#79 Add declare png
  src/global.d.ts
Labels: bug, build

#82 Сделана адаптация для админ панели
  src/pages/AdminUserPage/AdminUserPage.tsx
  src/pages/AdminUserPage/UI/UserItem/userItem.module.css
  src/pages/AdminUserPage/adminUserPage.module.css
  src/shared/components/Header/HeaderMobile/HeaderMobile.tsx
  src/shared/components/Header/HeaderMobile/headerMobile.module.css
  src/shared/components/Header/HeaderMobile/useHeaderMobile.ts
  src/shared/layouts/RootLayout/RootLayout.tsx
  src/shared/layouts/RootLayout/rootLayout.module.css
Labels: feature, design, refactoring

#83 Сделана адаптация групп для мобильных телефонов
  src/shared/components/EmailGroup/UI/CreateEmailGroupModal/createEmailGroupModal.module.css
  src/shared/components/Header/HeaderMobile/HeaderMobile.tsx
  src/shared/layouts/RootLayout/rootLayout.module.css
Labels: feature, design

#85 Сделана адаптация для страницы с настройками
  src/pages/SettingsPage/UI/AddTwoFactor/addToFactor.module.css
  src/pages/SettingsPage/UI/ChangePasswordForm/changePasswordForm.module.css
  src/pages/SettingsPage/UI/ChangeTheme/changeTheme.module.css
  src/pages/SettingsPage/UI/SettingWrapper/settingWrapper.module.css
Labels: bug, design

#86 Fix build
  package.json
Labels: build

#84 Сделана фильтрация писем
  src/App.tsx
  src/entities/Email/slices/emailSlice.ts
  src/index.css
  src/pages/AdminUserPage/adminUserPage.module.css
  src/pages/LettersPage/LettersPage.tsx
  src/pages/LettersPage/lettersPage.module.css
  src/pages/LettersPage/useLettersPage.ts
  src/pages/SentEmailsPage/SentEmailsPage.tsx
  src/pages/SentEmailsPage/useSentEmailsPage.ts
  src/pages/SettingsPage/UI/AddTwoFactor/addToFactor.module.css
  src/pages/SettingsPage/UI/ChangePasswordForm/changePasswordForm.module.css
  src/pages/SettingsPage/UI/ChangeTheme/changeTheme.module.css
  src/pages/SettingsPage/UI/SettingWrapper/settingWrapper.module.css
  src/pages/auth/AuthPage/UI/TwoFactorAuth/twoFactorAuth.module.css
  src/pages/auth/AuthPage/useAuthPage.ts
  src/pages/auth/RegistrationPage/registrationPage.module.css
  src/shared/components/ Switch/switch.module.css
  src/shared/components/Email/Email.tsx
  src/shared/components/EmailGroup/UI/CreateEmailGroupModal/createEmailGroupModal.module.css
  src/shared/components/Header/HeaderDesktop/HeaderDesktop.tsx
  src/shared/components/Header/HeaderMobile/HeaderMobile.tsx
  src/shared/components/Mailbox/mailbox.module.css
  src/shared/layouts/RootLayout/RootLayout.tsx
  src/shared/layouts/RootLayout/useRootLayout.ts
  src/shared/services/FormatterService.ts
Labels: feature
